export const popularStarWarsInfo = {
  characters: [
    "Aarrba the Hutt",
    "Adi Gallia",
    "Admiral Ackbar",
    "Admiral Daala",
    "Admiral Firmus Piett",
    "Admiral Kendal Ozzel",
    "Admiral Motti",
    "Admiral Raddus",
    "Agent Kallus",
    "Ahsoka Tano",
    "Aldar Beedo",
    "Allegiant General Pryde",
    "Anakin Skywalker",
    "Arihnda Pryce",
    "Asajj Ventress",
    "BB-8",
    "BB-9E",
    "Bail Organa",
    "Beru Lars",
    "Bib Fortuna",
    "Biggs Darklighter",
    "Bo-Katan Kryze",
    "Boba Fett",
    "Boss Nass",
    "Bossk",
    "C-3PO",
    "Cad Bane",
    "Captain Antilles",
    "Captain Panaka",
    "Captain Phasma",
    "Captain Typho",
    "Cassian Andor",
    "Chewbacca",
    "Chirrut Îmwe",
    "Cliegg Lars",
    "Cody",
    "Count Dooku",
    "DJ",
    "Darth Bane",
    "Darth Maul",
    "Darth Nihilus",
    "Darth Plagueis",
    "Darth Revan",
    "Darth Sidious",
    "Darth Tyranus",
    "Darth Vader",
    "Depa Billaba",
    "Dengar",
    "Echo",
    "Fode and Beed",
    "Finn",
    "Fives",
    "Galen Erso",
    "Gar Saxon",
    "General Grievous",
    "General Hux",
    "General Maximilian Veers",
    "General Redd Wessel",
    "General Rom Mohc",
    "General Crix Madine",
    "Grand Admiral Thrawn",
    "Grand Moff Tarkin",
    "Greedo",
    "Han Solo",
    "Hunter",
    "IG-88",
    "Jabba the Hutt",
    "Queen Jamillia",
    "Jango Fett",
    "Jar Jar Binks",
    "Jek Porkins",
    "Jyn Erso",
    "K-2SO",
    "Kit Fisto",
    "Ki-Adi-Mundi",
    "Kylo Ren",
    "Lannik",
    "Lando Calrissian",
    "Lobot",
    "Lomi Plo",
    "Luke Skywalker",
    "Lyra Erso",
    "Mace Windu",
    "Mas Amedda",
    "Maz Kanata",
    "Micah Giiett",
    "Moff Jerjerrod",
    "Moff Gideon",
    "Mon Mothma",
    "Nien Nunb",
    "Nute Gunray",
    "Obi-Wan Kenobi",
    "Omega",
    "Owen Lars",
    "Padme Amidala",
    "Plo Koon",
    "Prime Minister Lama Su",
    "Poe Dameron",
    "Qui-Gon Jinn",
    "Quinlan Vos",
    "R2-D2",
    "R5-D4",
    "Rex",
    "Rey",
    "Rose Tico",
    "Saw Gerrera",
    "Sebulba",
    "Shaak Ti",
    "Shmi Skywalker",
    "Sifo-Dyas",
    "Supreme Leader Snoke",
    "TC-14",
    "Thrawn",
    "Vice Admiral Amilyn Holdo",
    "Watto",
    "Wedge Antilles",
    "Yaddle",
    "Yarael Poof",
    "Yoda",
    "Zam Wesell",
    "Zekk",
  ],
  species: [
    "Amani",
    "Balosar",
    "Besalisk",
    "Bothan",
    "Chiss",
    "Clawdite",
    "Dug",
    "Ewok",
    "Arkanian",
    "Gamorrean",
    "Jawas",
    "Human",
    "Lannik",
    "Mon Calamari",
    "Quermian",
    "Toydarian",
    "Tuskan",
    "Twi'lek",
    "Umbaran",
    "Zabrak",
  ],
  planets: [
    "Ahch-To",
    "Alderaan",
    "Ankhural",
    "Anaxes",
    "Anoat",
    "Corellia",
    "Coruscant",
    "Dagobah",
    "Dantooine",
    "Dathomir",
    "Eadu",
    "Exegol",
    "Felucia",
    "Forest Moon of Endor",
    "Gamorr",
    "Geonosis",
    "Hoth",
    "Jakku",
    "Kamino",
    "Kashyyyk",
    "Kessel",
    "Kuat",
    "Lothal",
    "Lysatra",
    "Malastare",
    "Mandalore",
    "Mon Cala",
    "Naboo",
    "Ord Mantell",
    "Quermia",
    "Rodia",
    "Tatooine",
    "Toydaria",
    "Trandosha",
    "Umbara",
  ],
  battles: [
    "Jedi–Zygerrian conflict",
    "Hundred-Year Darkness",
    "Devastation of Parnassos",
    "Sith War",
    "Battle of Coruscant",
    "Great Scourge of Malachor",
    "Mandalorian-Jedi War",
    "Mandalorian crusades",
    "Devastation of Ubduria",
    "Mandalorian cataclysm",
    "Entruvia Conflict",
    "Battle of Takodana",
    "Jedi-Sith War",
    "Battle of Coruscant",
    "Liberation of Coruscant",
    "War on unidentified planet (Vagadarr system)",
    "Mission to unidentified planet",
    "Mandalorian Civil War",
    "Greater Seswenna raids",
    "Skirmish in the Kellux system",
    "Altercation on Nar Shaddaa",
    "Auction of Eldra Kaitis",
    "Skirmish on the moon of Drazkel",
    "Mission to Halcyon",
    "Mission to Oba Diah",
    "Invasion of Naboo",
    "Capture of Theed",
    "Attack on Otoh Langua",
    "Duel on Tatooine",
    "Battle of Naboo",
    "Mission to Dallenor",
    "Open-Closed War",
    "Mission to Carnelion IV",
    "Separatist Crisis",
    "Antar 4 schism",
    "Border dispute on Ansion",
    "Plot to assassinate Padmé Amidala",
    "Mission to Kamino",
    "Dogfight over Geonosis",
    "Mission to rescue Shmi Skywalker Lars",
    "First Battle of Geonosis",
    "Attack on a Republic troop transport",
    "Battle of Arantara",
    "Battle of Murkhana",
    "Battle in the Corvair sector",
    "Mission to Kudo III",
    "Siege of Hisseen",
    "Battle of Christophsis",
    "Battle of Teth",
    "Mission to Jabba's Palace",
    "Raid on Ziro's Palace",
    "Battle of Aargonar",
    "Battle of Ryloth",
    "Ambush on Rugosa",
    "Battle of Abregado",
    "Battle of the Ryndellia system",
    "Battle of the Kaliida Nebula",
    "Battle near the Kaliida Nebula",
    "Battle of Mimban",
    "Defense of Rishi Station",
    "Battle of Falleen",
    "Battle of Bothawui",
    "Ambush on the Vulture's Claw",
    "Mission to sweep outer corridor of space",
    "Mission to Skytop Station",
    "Mission to Rodia",
    "Rescue on the Tranquility",
    "Mission to Vassek 3",
    "Skirmish at Vanqor",
    "Mission to Florrum",
    "Battle of Quell",
    "Defense of Maridun",
    "Skirmish on Orto Plutonia",
    "Battle of Orto Plutonia",
    "Siege of Grange",
    "Mission to Merj",
    "Rescue of Galen Erso",
    "Raid on Nuvo Vindi's laboratory",
    "Mission to Iego",
    "First Battle of Felucia",
    "Raid on the Jedi Temple",
    "Battle of Devaron",
    "Mission to Glee Anselm",
    "Mission to Naboo",
    "Second Mission to Rodia",
    "Mission to Mustafar",
    "Mission to Black Stall Station",
    "Destruction of Felucia Medical Station HCTFF2",
    "Skirmish on Felucia",
    "Battle of Malastare",
    "Zillo Beast incident",
    "Mission to Cato Neimoidia",
    "Battle near Dorin",
    "Second Battle of Geonosis",
    "Defense of Dantooine",
    "Skirmish aboard TB-73",
    "Capture of Eeth Koth",
    "Battle of Saleucami",
    "Attack on a Republic cruiser",
    "Bombing of the Memorial Shrine",
    "Skirmish on Concordia",
    "Skirmish aboard the Coronet",
    "Plot to assassinate Satine Kryze",
    "Bombing on Kalevala",
    "Sabotage of the Endurance",
    "Mission to Vanqor",
    "Second mission to Florrum",
    "Skirmish at the Sundari docks",
    "Mandalorian black market conspiracy",
    "Balith civil war",
    "Alderaan Refugee Conference",
    "Battle of Kamino",
    "Blockade of Pantora",
    "Kidnapping of the Papanoida daughters",
    "Rescue on the Pantora Droid Control Ship",
    "Rescue in Chalmun's Cantina",
    "Senate hostage crisis",
    "Showdown on Teth",
    "Bombing of Coruscant's central power distribution grid",
    "Attack on Confederate people",
    "Battle of Sullust",
    "Mission to Serenno",
    "Devaron massacre",
    "Showdown at Toydaria",
    "Mission to Mortis",
    "Capture of Even Piell",
    "Battle of Lola Sayu",
    "Second Battle of Felucia",
    "Skirmish on Wasskah",
    "Battle of Mon Cala",
    "Skirmish on Naboo",
    "Battle of Patitite Pattuna",
    "Rescue of Adi Gallia",
    "Battle of Umbara",
    "Battle of Kiros",
    "Battle of Zygerria",
    "Battle of Kadavo",
    "Battle on Carlac",
    "Riot at the Republic Judiciary Central Detention Center",
    "Showdown on Orondia",
    "Skirmish in Theed",
    "Battle of Dathomir",
    "Safe cargo objective",
    "Mission to Lotho Minor",
    "Massacre on Raydonia",
    "Skirmish above Raydonia",
    "Onderonian Civil War",
    "Raid on the Crucible",
    "Attack on Obi-Wan Kenobi's fleet",
    "Rescue on Florrum",
    "Battle on Florrum",
    "Battle over unidentified planet",
    "Mission to Aut-O's flagship",
    "Escape from Abafar",
    "Carida incident",
    "Duel at unidentified Outer Rim spaceport",
    "Raid on the Cybloc Transfer Station",
    "Skirmish on Florrum",
    "Mission to Mustafar",
    "Mission to Nal Hutta",
    "Attack on Jabba's Palace",
    "Takeover of Mandalore",
    "Mandalorian civil war",
    "Defense of Cato Neimoidia",
    "Bombing of the Jedi Temple hangar",
    "Escape from the Republic military base",
    "Duel at the Jedi Temple",
    "Battle of Ringo Vinda",
    "Mission to Level 1325",
    "Mission to Scipio",
    "Invasion of Scipio",
    "Mission to Bardotta",
    "Mission to Zardossa Stix",
    "Mission to Oba Diah",
    "Mission to Moraband",
    "Mission to Utapau",
    "Atrocity on Mahranee",
    "Capture of Moregi",
    "Rescue of Marg Krim's family",
    "Mission to Raxus Secundus",
    "Escape from the Spire",
    "Battle of Zanbar",
    "Battle of Ord Mantell",
    "Assault on Vizsla Keep 09",
    "Second Battle of Dathomir",
    "Mission to Serenno",
    "Rescue of Quinlan Vos",
    "Destruction of the Separatist supply storage base",
    "Destruction of the Vanqor listening post",
    "Second battle of Christophsis",
    "Battle of Haruun Kal",
    "Insurrection on Yalbec Prime",
    "Battle of Anaxes",
    "Mission to Skako Minor",
    "Bombing at the Jedi Temple",
    "Skirmish on Kardoa",
    "Third Battle of Mygeeto",
    "Battle on Lokori",
    "Escape from Geonosis",
    "Battle of Yerbana",
    "Battle of Coruscant",
    "Siege of Mandalore",
    "Attack in an unidentified sector",
    "Outer Rim Sieges",
    "Battle of Utapau",
    "Battle of Cato Neimoidia",
    "Battle of Kashyyyk",
    "Assault on Mygeeto",
    "Siege of Saleucami",
    "Battle of Felucia",
    "Conquest of Kaller",
    "Duel in Palpatine's office",
    "Great Jedi Purge",
    "Siege of the Jedi Temple",
    "Skirmish aboard the Tribunal",
    "Mission to Mustafar",
    "Great Jedi Purge",
    "Imperial Era",
    "Duel on Mustafar",
    "Duel in the Galactic Senate",
    "Recapture of Vader's starship",
    "Attack on Brighthome",
    "Mission to Al'doleem",
    "Hunt for Jocasta Nu",
    "Assassination attempts on Darth Vader",
    "Ambush in the Coruscant system",
    "Theft of the IG-RM droids",
    "Rescue of Caleb Dume",
    "Antar Atrocity",
    "Western Reaches pacification operations",
    "Hunt on Chandar's Folly",
    "Hunt for Eeth Koth",
    "Rogue Inquisitor chase",
    "Capture of Galen Erso",
    "Battle of Fortress Vader",
    "Annexation of Jelucan",
    "Mimban campaign",
    "Heist on Vandor",
    "Raid on Kessel",
    "Showdown on Savareen",
    "Garel statue protest",
    "Great Jedi Purge",
    "Early rebellion against the Galactic Empire",
    "Rebellion on Umbara",
    "Campaigns of Saw Gerrera's Partisans",
    "Campaign at Salient",
    "Invasion of Mon Cala",
    "Battle of Dac City",
    "Attack on Bergon's sky-base",
    "Skirmish in Bel City",
    "Duel in the Royal Command Bunker",
    "Raada Uprising",
    "Heist at the Twin Horns Storage",
    "Ryloth summer riots",
    "Mission to hijack an Imperial weapons shipment",
    "Mission to Ryloth",
    "Secret mission to rebuild the Jedi Order",
    "Berch Teller campaign",
    "Attack on Sentinel Base",
    "Mission to Murkhana",
    "Attack on Galidraan Station",
    "Attack on Lucazec",
    "Battle in the Phindar system",
    "Attack on the Nouane system",
    "Battle near the Gulf of Tatooine",
    "Relief mission to Ryloth",
    "Gorse conflict",
    "Raid on Gargon",
    "Mimban campaign",
    "Mission to Horuz",
    "Mission to Inusagi",
    "Malkhani Insurrections",
    "Westhills bombing attempt",
    "Westhills massacre",
    "Westhills skirmish",
    "Attack on Imperial interrogator droids",
    "Transportation Ministry data breach",
    "Raid on an Imperial supply convoy",
    "Attack on a Lothal airfield",
    "Heist in Capital City",
    "Mission to free Wookiee prisoners",
    "Mission to steal Imperial weapons",
    "Attack on Imperial Troop Transports",
    "Duel on Stygeon Prime",
    "Mission to destroy a kyber crystal",
    "Attack on an Imperial convoy",
    "Skirmish on Vyndal",
    "Bombing at the Empire Day parade",
    "Rescue of Tseebo",
    "Mission to Lando Calrissian's farm",
    "Assault on the Gray Syndicate",
    "Trap in the Old Republic Senate Building",
    "Raid near Jalath",
    "Raid on the communications tower",
    "Action at Mustafar",
    "Rescue of Dhara Leonis",
    "Mission to rescue Janard",
    "Mission to steal Imperial shield generators",
    "Siege of Lothal",
    "Mission to Lothal",
    "Attack on Phoenix Squadron",
    "Assault on Seelos",
    "Mission to Absanz",
    "Skirmish aboard a Republic medical station",
    "Skirmish in Nixus Hub 218",
    "Blockade of Ibaar",
    "Skirmish on Thrad",
    "Skirmish in the Garel City Spaceport",
    "Rescue on the Imperial Interdictor",
    "Battle with Phoenix Squadron",
    "Duel in Hammertown",
    "Skirmish on Imvur",
    "Duel on Bilzen",
    "Revolt in an Imperial prison",
    "Battle of Garel",
    "Attack on Calderos",
    "Assassination of Quarsh Panaka",
    "Arrests on Christophsis",
    "Evacuation of Paucris Major",
    "Auction on Cantonica",
    "Mission to Garel",
    "Mission on Lothal",
    "Dogfight over Concord Dawn",
    "Mission to the third moon of Concord Dawn",
    "Rediscovery of Lira San",
    "Heist at the Asteroid Belt Gas Refinery",
    "Mission to Ryloth",
    "Ambush on an Imperial construction module",
    "Duel on Oosalon",
    "Rescue of Ezra Bridger",
    "Attack on Phoenix Squadron",
    "Mission to Thune City",
    "Mission to Malachor",
    "Batonn sector insurgency",
    "Battle of Denash",
    "Battle of Sammun",
    "Batonn insurgency",
    "Battle of Scrim Island",
    "Siege of the Creekpath Mining and Refining complex",
    "Rescue of Hondo Ohnaka",
    "Mission to Reklam Station",
    "Maul's capture of the Ghost crew",
    "Massacre near Teralov",
    "Escape from Skystrike Academy",
    "Second mission to Ryloth",
    "Mission to Agamar",
    "Second mission to the third moon of Concord Dawn",
    "Skirmish over Mykapo",
    "Blockade over Synistahg",
    "Mission to loot an Imperial cargo ship",
    "Infiltration of the Imperial Armory Complex",
    "Skirmish on Dathomir",
    "Rescue of Ketsu Onyo",
    "Mission to investigate Geonosis",
    "EXD-9's infiltration of Chopper Base",
    "Mandalorian Civil War",
    "Skirmish on Krownest",
    "Rescue of Alexsandr Kallus",
    "Ghorman Massacre",
    "Operation Handoff",
    "Mission to recover Imperial codes",
    "Mission to Tatooine",
    "Battle of Atollon",
    "Imperial–Grysk conflict",
    "Skirmish on Batuu",
    "Battle of Mokivj",
    "Battle against Grysk forces",
    "Mandalorian Civil War",
    "Mission to Mandalore",
    "Mission to Jalindi",
    "Mission to Faos Station",
    "Theft of the TIE Defender Elite",
    "Hijacking of Crawler 413-24",
    "Attack on Lothal",
    "Rescue of Hera Syndulla",
    "Mission to the Lothal Jedi Temple",
    "Liberation of Lothal",
    "Battle of the Tower",
    "Battle of Phindar",
    "Battle of Portocari",
    "Discovery of the Death Star",
    "Jedha insurgency",
    "Battle of Jedha City",
    "Mission to the Ring of Kafrene",
    "Liberation of Erso",
    "Operation Fracture",
    "Battle on Jedha",
    "Destruction of Jedha City",
    "Mission to Eadu",
    "Great Jedi Purge",
    "Ryloth Insurgency",
    "Galactic Civil War",
    "Battle of Scarif",
    "Secret mission to Tatooine",
    "The Disaster",
    "Alderaan vigil rioting",
    "Rescue of Princess Leia",
    "Battle of Yavin",
    "Ambush on Taanab",
    "Evacuation of Yavin 4",
    "Mission to rescue the survivors of Alderaan",
    "Mission to Giju",
    "Mission to recover Imperial communication logs",
    "Skirmish in the Temple of Eedit",
    "Skirmish over Llanic",
    "Mission to Rodia",
    "Mission to Fex",
    "Mission on Denon",
    "Mission to Pasher",
    "Mission to Omereth",
    "Assault on Cymoon",
    "Skirmish over an unidentified green planet",
    "Attack on an unidentified pirate base",
    "Theft of the Triple-Zero protocol personality matrix",
    "Secret mission to Geonosis",
    "Skirmish in Cylo's research base",
    "Duel in Ben Kenobi's home",
    "First attack on the Son-tuul Pride",
    "Bombing of an Imperial supply base",
    "Bombing of the Kuat shipyards",
    "Son-tuul Pride robbery",
    "Escape from the Monsua Nebula",
    "Mission to the Anthan system",
    "Rescue of Luke Skywalker",
    "Mission to Shu-Torun",
    "Battle of Vrogas Vas",
    "Arrth-Eno Mission",
    "Assault on Sunspot Prison",
    "War on Shu-Torun",
    "Battle at a delving citadel",
    "Attack on the ancestral retreat",
    "Battle at Rubix's citadel",
    "Hijacking of the Executor",
    "Skirmish on the Ghost Moon",
    "Hijacking of the Harbinger",
    "Siege on Tureen VII",
    "Escape from Skorii-Lei",
    "Mission to rescue C-3PO",
    "Mission to unidentified planet",
    "Raid at the Great Temple",
    "Twilight of the Ordu Aspectu",
    "Mission to Ktath'atn",
    "Skirmish aboard the Sorca Retreat",
    "Escape from an unidentified ocean planet",
    "Liberation of Grakkus",
    "Mission to Akiva",
    "Mission to Horox III",
    "Mission to Crait",
    "Arrests on Zeitooine",
    "Attack on an EF76 Nebulon-B escort frigate",
    "Bandit purges",
    "Attack on a pirate station",
    "Skirmish aboard Accresker Jail",
    "Mid Rim Retreat",
    "Battle for Jedha",
    "Mutiny on Mon Cala",
    "Assault on the Mako-Ta Space Docks",
    "Skirmish on Hubin",
    "Attack on an Imperial Impound Yard",
    "Attack on Haidoral Prime",
    "Battle in the Kontahr sector",
    "Coyerti campaign",
    "Attack on an Imperial scout post",
    "Attack on an Imperial fort",
    "Attack on the Distillery",
    "Destruction of the Coyerti Imperial garrison",
    "Battle in the Metatessu sector",
    "Battle in the Enrivi system",
    "Battle in the Chonsetta system",
    "Raid on an Imperial heavy freighter",
    "Infiltration of the Thunderstrike",
    "Battle of Hoth",
    "Duel on Cloud City",
    "Escape from Cloud City",
    "Operation Ringbreaker",
    "Attack on Mardona III",
    "Attack on the dockyards of Najan-Rovi",
    "Attack on Obumubo",
    "Attack on Nakadia",
    "Battle of Naator",
    "Battle of Xagobah",
    "Attack on the Kuliquo belt asteroid mines",
    "Siege of Inyusu Tor",
    "Operation Yellow Moon",
    "Destruction of the Shieldmaiden",
    "Rescue of Han Solo",
    "Battle of Taanab",
    "Dogfight in the Hudalla system",
    "Bombardment of Durkteel",
    "Battle of Endor",
    "Coruscant civil war",
    "Riot in Monument Plaza",
    "Assault on an Imperial outpost",
    "Beltire Liberation",
    "Battle of Cawa City",
    "Raid at the Wretch of Tayron",
    "Defense of the Victorum",
    "Contingency",
    "Operation: Cinder",
    "Battle of Fondor",
    "Skirmish on Vardos",
    "Battle of Theed",
    "Attack on Abednedo",
    "Attack on Burnin Konn",
    "Iron Blockade",
    "Liberation of Cloud City",
    "Attempted kidnapping of Bragh",
    "Rescue mission to the Crypt",
    "Battle of Mataou",
    "Battle of Hoth (Iron Blockade)",
    "Battle of Anoat",
    "Battle of Malastare",
    "Battle of Naalol",
    "Operation on Geonosis",
    "Battle in Central City",
    "Battle of Sevarcos",
    "Mission to Akiva",
    "Rebellion on Akiva",
    "Mission to Vetine",
    "Skirmish on Takodana",
    "Attack on the Hyborean Moon",
    "Capture of Perwin Gedde",
    "Skirmish near Wild Space",
    "Battle of Nag Ubdur",
    "Ambush at Govneh Ridge",
    "Massacre at Binjai-Tin",
    "Coronet City revolution",
    "Attack on a New Republic outpost",
    "Siege of Arkanis",
    "Battle for Kuat Drive Yards",
    "Liberation of Kashyyyk",
    "Imperial-Republic peace talks",
    "Attack on Chandrila",
    "Mission to Chinook Station",
    "Destruction of an abandoned weapons depot",
    "Capture of Mercurial Swift",
    "Liberation of Nakadia",
    "Mission to Nakadia",
    "Skirmish in Freetown",
    "Naboo invasions",
    "Battle of Fondor Shipyards",
    "Assassination attempt on Mon Mothma",
    "Destruction of Imperial Star Destroyers",
    "Contingency",
    "Battle of Jakku",
    "New Republic Era",
    "Karee Blockade Clutch",
    "Hunt for Fyzen Gor",
    "Standoff near Substation Grimdock",
    "Second skirmish in the Mesulan Remnants Belt",
    "Hunt for Grogu",
    "Mission to Arvala-7",
    "Rescue of Grogu",
    "Skirmish on Tython",
    "Skirmish on Sorgan",
    "Hunt for Fennec Shand",
    "Rescue of Qin",
    "Skirmish on Nevarro",
    "Assault on the Imperial Gozanti freighter",
    "Second skirmish on Nevarro",
    "Liberation of Calodan",
    "Quest for Exegol",
    "Mission to Pasaana",
    "Mission to Parnassos",
    "Amaxine warrior crisis",
    "Mission to Bastatha",
    "Napkin Bombing",
    "Mission to Sibensko",
    "Tai-Lin Garr's assassination",
    "Destruction of the Jedi Temple",
    "Duel on Elphrona",
    "Skirmish on the Minemoon",
    "Cold War",
    "Race for the Lost Treasure of Count Dooku",
    "Suraz engagement",
    "Skirmish in OR-Kappa-2722",
    "Mission to Taul",
    "Rescue of Admiral Ackbar",
    "Operation: Sabre Strike",
    "Hunt for Lor San Tekka",
    "Mission to Ovanis",
    "Mission to Megalox Beta",
    "Skirmish on Pheryon",
    "Mission to Kaddak",
    "Battle over a desert planet",
    "Mission to obtain fuel",
    "Mission to Spalex",
    "Hunt for Lor San Tekka",
    "Mission to Cato Neimoidia",
    "Rescue of Lor San Tekka",
    "Mission to rendezvous with the Resistance",
    "Mission on the Colossus platform",
    "Raid on the Colossus",
    "Mission to Doza Tower",
    "Second raid on the Colossus",
    "Second mission to Doza Tower",
    "Massacre on Tehar",
    "Hunt for Eila and Kel",
    "Investigation of a G-class freighter",
    "Mission on the Colossus platform",
    "Second raid on the Colossus",
    "Second mission to Doza Tower",
    "Mission to Station Theta Black",
    "Mission on the Colossus platform",
    "Theft of the phase connector",
    "Kidnapping of Torra Doza",
    "Occupation of the Colossus",
    "Escape from the Colossus",
    "Mission to the Dassal system",
    "Occupation of the Colossus",
    "Rescue on the Colossus",
    "Mission to contact the Resistance",
    "Missions against pirates in the Cassander sector",
    "Battle of Mamkoda",
    "Mission to Caraxl",
    "Strike at Pressy's Tumble",
    "Hunt for Lor San Tekka",
    "Mission to Pillio",
    "Attack on Tuanul",
    "Missions against pirates in the Cassander sector",
    "Battle of Sheh Soahi",
    "Escape from the Finalizer",
    "Escape from Jakku",
    "Skirmish aboard the Eravana",
    "Mission to Athulla",
    "Mission to Vodran",
    "First Order/Resistance War",
    "Hosnian Cataclysm",
    "Battle of Kestro",
    "Atterra campaign",
    "Battle of Takodana",
    "Attack on Castilon",
    "Skirmish on the Retribution",
    "Battle of Starkiller Base",
    "Hunt for Rivas",
    "Mission to the Outer Rim",
    "Battle on Pastoria",
    "Battle of D'Qar",
    "Hunt for the Colossus",
    "Skirmish over D'Qar",
    "Sabotage of the Colossus",
    "Skirmish by a signal beacon",
    "Mission to Canto Bight",
    "Attack on the Resistance fleet",
    "Battle of Crait",
    "Mission to the Outer Rim",
    "Battle of Grail City",
    "Mission to Batuu",
    "Heist on a First Order train",
    "Attack on Aeos Prime",
    "Hunt for the Colossus",
    "Escape from Aeos Prime",
    "Suppression of the Aeos system",
    "Rescue of Tamara Ryvora",
    "Blockade of Dantooine",
    "Mission to obtain the Sith wayfinder",
    "Mission to Sinta Glacier Colony",
    "Mission to Pasaana",
    "Mission to Kijimi",
    "Mission to Kef Bir",
    "Destruction of Kijimi",
    "Battle of Exegol",
    "Uprising against the First Order",
    "Uprising on Cloud City",
    "Uprising on Corellia",
    "Uprising on Coruscant",
    "Uprising on Endor",
    "Uprising on Jakku",
    "Uprising on Lothal",
    "Uprising on Naboo",
    "Uprising on Thyferra",
    "Battles of Rashfond",
    "Peacekeeping of Parliock",
    "Doom of the Ordu Aspectu",
    "Encounter in the Senex-Juvex",
    "Battle of Malastare Narrows",
    "Mission to the moons of Sanjin",
    "Conflict on Bri'n",
    "Grysk conquests",
    "Naboo miners' strikes",
    "Darth Momin's destruction of a city",
    "Battle of Agamar",
    "Battle of Akiva",
    "Battle of Hypori",
    "Battle of Khorm",
    "Battle of Nal Kapok",
    "Attack on Phindar",
    "Sneak attack on Roche",
    "Battle of Sarrish",
    "Battle of Sedratis",
    "Attack on the Coruscant Separatist cell",
    "Battle of Slag's Pit",
    "Battle of unidentified planet",
    "Battle of Zequardia",
    "Skirmish on Oktaro",
    "Mission to Clabron",
    "Destruction of the Ledeve Jedi Temple",
    "Destruction of Anaxes",
    "Onderon insurgency",
    "Siege of Lasan",
    "Battle of Maraken",
    "Sterilization of Geonosis",
    "Massacre on Kashyyyk",
    "Wookiee revolt",
    "Dhen-Moh genocides",
    "Belnar Insurrections",
    "Subjugation of the Anoat sector",
    "Gassing of Anoat",
    "Culroon III campaign",
    "Battle of Fanha",
    "Battle of Tosste",
    "Battle of Ogoth Tiir",
    "Pacification of Bryndar",
    "Battle of Foerost",
    "Circle Bay mayor's office protest",
    "Cyphar Incident",
    "Battle over Umbara",
    "Battle at Lansend Twenty-Six",
    "Attack on the Sempre",
    "Assault on Winter's Edge",
    "Uprising on Cherridan",
    "Infiltration of Iakar",
    "Battle of Ferrok Pax",
    "Assault on Garel",
    "Assault on Ord Biniir",
    "Zaloriis campaign",
    "Mission to Fekunda Outpost",
    "First skirmish in the Mesulan Remnants Belt",
    "Battle on Baltro",
    "Pasa Novo campaign",
    "Old Market Sector riots",
    "Battle of Mygeeto",
    "Battle of Phorsa Gedd",
    "Chargona campaign",
    "Decimation on Magnus Horn",
    "Massacre at Asyrphus",
    "Skirmish on Tatooine",
    "Theft of the Imperialis",
    "Mission to Circarpous",
    "Attack on Saponza's homestead",
    "Attack on a Tusken Raider camp",
    "Mission to recover medical supplies",
    "Undead Troopers invasion",
    "Mission to cull womp rats",
    "Sneak attack on Saponza's homestead",
    "Battle of Allst Prime",
    "Battle of Blacktar Cyst",
    "Cargamalis Street Wars",
    "Assault on Vivonah",
    "Slaughter on Noult",
    "Liberation of Gorma",
    "Operation: Mynock Bite",
    "Mexeluine riots",
    "Battle at Castilon",
    "Battle over Kuat",
    "Operation Mad Rush",
    "Dandoran campaign",
    "The Jundland General's campaign",
    "Operations against Tatooine mercenaries",
    "Mission to Tatooine",
    "Rescue of R2-D2",
    "Mission to Vashka",
    "Skirmish of Adratharpe 7",
    "Skirmish at the abandoned Jakku moisture farm",
    "Trillia Massacre",
    "Attack on Demir",
  ],
  moviesAndShows: [
    "Acolyte",
    "The Phantom Menace",
    "Attack of the Clones",
    "Yoda Chronicles",
    "The Clone Wars",
    "Revenge of the Sith",
    "Bad Batch",
    "Solo",
    "Kenobi",
    "Rebels",
    "Andor",
    "Rogue One",
    "A New Hope",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "The Mandalorian",
    "The Book of Boba Fett",
    "Ahsoka",
    "Resistance",
    "Resistance Rises",
    "The Force Awakens",
    "The Last Jedi",
    "The Rise of Skywalker",
    "Forces of Destiny",
  ],
  monsters: [
    "Sarlacc",
    "Rancor",
    "Nexu",
    "Mudhorn",
    "Zillow Beast",
    "Loth Wolf",
    "Rathtar",
    "Wampa",
    "Krayt Dragon",
  ],
};
